### ISSUE TITLE
Out of Date

### ISSUE THREAD

**Issue by Arasiya** [zippity21/Stardew_Valley_Regression_Mod#108]
My SMAPI is telling me it can't load the mod because it is not up to date. I have the latest version and have only ever downloaded that version. Is it currently in need of an update or has something gone wrong on my end?

**Comment by Wimsik** [comment]
Ran into this while helping a friend install the other day as well. In our case, the out of date error was due to downloading PyTK Lite instead of PyTK Original. Give these steps a shot and see if they work:

1. Remove/Delete your current PyTK folder from your \Stardew Valley\Mods folder
2. Go here: https://www.nexusmods.com/stardewvalley/mods/1726?tab=files
3. Download the first thing under Optional Files, PyTK - Platonymous Toolkit/"Original version".
4. Unzip the PyTK folder into your \Stardew Valley\Mods folder
5. Try and launch through SMAPI again.

Hope this helps!

**Comment by chaos-demon** [comment]
I'd also like to add that I've noticed a warning when I load SMAPI that the next major update will not support PyTK original so fair warning that things may stop working after that if this mod isn't patched to work with PyTK Lite or something else before the next SMAPI update
