### ISSUE TITLE
Balance Incontinence Risk/Reward

### ISSUE THREAD

**Issue by zippity21** [zippity21/Stardew_Valley_Regression_Mod#3]
Given the target community, it is expected that most will try to become incontinent as quickly as possible. This is likely to make the process of slowly losing continence feel like a mere inconvenience.

I recommend making more consequences for losing continence, to give players an incentive to stay dry. The challenge of this mod is to balance hunger, thirst, time, energy, and the need to pee. So, if there is no punishment for not using the big-kid potty, why would anyone try to take it into consideration?

**Comment by LilBearBlue** [comment]
I feel that this request discounts the player-base that isn't playing ABDL mods for increased difficulty. Some people just want to roleplay as a diapered Stardew character. Others (myself included on this one) may just want to roleplay going through gradually declining continence in a lifesim-style game and enjoy the day-to-day diaper management aspects.

Not saying that there shouldn't necessarily be applicable in-game mechanics regarding diapers (bed drying, cost of diapers, social consequences, and speed and defense decreases for blowouts and wet leaks all being good examples), but I worry that putting too many or too harsh of consequences on diapers and accidents will only make the game more of a chore to play, rather than enhancing it.

**Comment by zippity21** [comment]
I suppose that's true. I put it here more as a potential suggestion. It probably belongs in the discussion section, but I hadn't set it up yet.

Perhaps not adding more consequences, but maybe just better balancing the existing ones, like:

- Stamina hit per wake-up at night
- Bed/cloth drying times based on messiness
- Duration and magnitude of debuffs
- Magnitude of social repercussions (both positive and negative)
- Cost of underwear
- Bladder, Bowel, Hunger and Thirst fill rates
- Effects of food & drink

I think you're right that there is enough there. I just don't know if things are as balanced as they should/could be. But I really need community feedback. So I think this is an open discussion, and I don't think I'll make any changes in the near future.
