### ISSUE TITLE
Can You make it for Smapi 3.12.8 aka SV version 1.5.4 so more mods can be played along side it?

### ISSUE THREAD

**Issue by OriginCosdenex15** [zippity21/Stardew_Valley_Regression_Mod#41]
I just feel like it should have been done like this from the start for more characters and outfits along side this mod, so if you could do that then that would be great.

**Comment by zippity21** [comment]
Unfortunately that would be a fairly large effort due to some underlying changes to the game's framework between 1.5.4 and 1.5.5. I decided to target 1.5.5 as to avoid having to do the additional porting work later, especially considering that 1.5.5 will likely be the final major release of the game (so targeting the new framework futureproofs it).

Hopefully it'll be out of beta soon and other mod maintainers will follow suit.

**Comment by OriginCosdenex15** [comment]
Still it might not come out fully for a while.

**Comment by zippity21** [comment]
1.5.5 has left beta and is now the primary version of the game. Thank you for your patience.
